format = """
$os\
$hostname\
[](bg:#DA627D fg:#444444)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[\n→ ](fg:#FCA17D)\
"""

[os]
disabled = false
style = "fg:#bbbbbb bg:#444444"

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[hostname]
ssh_only = false
format = '[ $hostname ](fg:#bbbbbb bg:#444444)'

[directory]
format = "[ $path ](fg:black bg:#DA627D)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[ $symbol $branch](fg:black bg:#FCA17D)'

[git_status]
format = '[ $all_status$ahead_behind](fg:black bg:#FCA17D)'
