format = """
[](#9A348E)\
$hostname\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[ ](fg:#FCA17D)\
"""

[hostname]
ssh_only = false
format = '[$hostname ](bg:#9A348E)'

[directory]
format = "[ $path ](fg:black bg:#DA627D)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[ $symbol $branch ](fg:black bg:#FCA17D)'

[git_status]
format = '[$all_status$ahead_behind ](fg:black bg:#FCA17D)'
