format = """
$hostname\
[](bg:#DA627D fg:#333333)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[\n→ ](fg:#FCA17D)\
"""

[hostname]
ssh_only = false
format = '[ $hostname ](bg:#333333)'

[directory]
format = "[ $path ](fg:black bg:#DA627D)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
format = '[ $symbol $branch](fg:black bg:#FCA17D)'

[git_status]
format = '[ $all_status$ahead_behind](fg:black bg:#FCA17D)'
